# policy_class: ACT
# policy_config:
#   lr: 1e-5
#   num_queries: 100
#   kl_weight: 10
#   hidden_dim: 512
#   dim_feedforward: 3200
#   lr_backbone: 1e-5
#   backbone: resnet18
#   enc_layers: 4
#   dec_layers: 7
#   nheads: 8
#   camera_names:
#     - ego_realsense
# stats_path: act/result/dataset_stats.pkl

# policy_config.yaml
policy_class: ACT
policy_config:
  lr:              !!float 1e-5
  num_queries:     !!int   10
  kl_weight:       !!float 10
  hidden_dim:      !!int   512
  dim_feedforward: !!int   3200
  lr_backbone:     !!float 1e-5
  backbone:        resnet18
  enc_layers:      !!int   4
  dec_layers:      !!int   7
  nheads:          !!int   8
  episode_len:          !!int   200
  camera_names:
    - ego_realsense
stats_path: /media/ansur/684845314844FEF6/Junho_IL_data/250802result/dataset_stats.pkl
ckpt_path : /media/ansur/684845314844FEF6/Junho_IL_data/250802result/policy_last.ckpt
